baseurl = "//v0-21.choerodon.io/"
title = "猪齿鱼Choerodon | 开源多云应用敏捷全链路技术平台"
theme = "choerodon-document-theme"
# themesDir = "../.."
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir= "true"
prettyurls=true
# Define the number of posts per page
paginate = 5
# Open highlight
#pygmentsCodeFences = true

[languages]
    [languages.en]
        languageName = "English"
    [languages.zh]
        languageName = "中文"

[menu]
# Main menu
[[languages.en.menu.main]]
    name = "Docs"
    url  = "/en/docs/"
    weight = 1

[[languages.en.menu.main]]
    name = "Blog"
    url  = "/en/blog/"
    weight = 2

[[languages.en.menu.main]]
    name = "Case Studies"
    url  = "/en/case-studies/"
    weight = 3

[[languages.en.menu.main]]
    name = "Community"
    weight = 4
    identifier = "en-community"
    pre = "<i class='iconfont'>&#xe600;</i>"
    [[languages.en.menu.main]]
	        name = "Community"
	        url  = "/en/community/"
	        weight = 5
	        parent = "en-community"
	[[languages.en.menu.main]]
	        name = "Knowledge-Sharing"
	        url  = "/en/knowledge-sharing"
	        weight = 6
	        parent = "en-community"

[[languages.en.menu.main]]
    name = "SourceCode"
    weight = 7
    identifier = "source"
    pre = "<i class='iconfont'>&#xe600;</i>"

    [[languages.en.menu.main]]
        name = "GITHUB"
        post= true
        url  = "https://github.com/choerodon/choerodon"
        weight = 8
        parent = "source"
    [[languages.en.menu.main]]
        name = "GITEE"
        post= true
        url  = "https://gitee.com/choerodon/choerodon"
        weight = 9
        parent = "source"

[[languages.en.menu.main]]
    name = "v0.22"
    url  = "/en/"
    weight = 10
    identifier = "en-version"
    pre = "<i class='iconfont'>&#xe600;</i>"
    [[languages.en.menu.main]]
        name = "v0.19"
        url  = "http://v0-19.choerodon.io/en/"
        weight = 12
        parent = "en-version"
    [[languages.en.menu.main]]
        name = "v0.20"
        url  = "http://v0-20.choerodon.io/en/"
        weight = 13
        parent = "en-version"
    [[languages.en.menu.main]]
        name = "v0.21"
        url  = "http://v0-21.choerodon.io/en/"
        weight = 14
        parent = "en-version"
    [[languages.en.menu.main]]
        name = "v0.22"
        url  = "http://v0-22.choerodon.io/en/"
        weight = 15
        parent = "en-version"

[[languages.zh.menu.main]]
    name = "文档"
    url  = "/zh/docs/"
    weight = 15

[[languages.zh.menu.main]]
    name = "博客"
    url  = "/zh/blog/"
    weight = 16

[[languages.zh.menu.main]]
    name = "案例"
    url  = "/zh/case-studies/"
    weight = 17

[[languages.zh.menu.main]]
    name = "社区"
    weight = 18
    identifier = "zh-community"
    pre = "<i class='iconfont'>&#xe600;</i>"
	[[languages.zh.menu.main]]
        name = "知识分享"
        url  = "/zh/knowledge-sharing"
        weight = 19
        parent = "zh-community"
	[[languages.zh.menu.main]]
        name = "社区"
        url  = "/zh/community/"
        weight = 20
        parent = "zh-community"

[[languages.zh.menu.main]]
    name = "源码"
    weight = 21
    identifier = "zh-source"
    pre = "<i class='iconfont'>&#xe600;</i>"
    [[languages.zh.menu.main]]
        name = "GITHUB"
        post= true
        url  = "https://github.com/choerodon/choerodon"
        weight = 22
        parent = "zh-source"
    [[languages.zh.menu.main]]
        name = "GITEE"
        post= true
        url  = "https://gitee.com/choerodon/choerodon"
        weight = 23
        parent = "zh-source"

[[languages.zh.menu.main]]
    name = "v0.22"
    url  = "/zh/"
    weight = 24
    identifier = "zh-version"
    pre = "<i class='iconfont'>&#xe600;</i>"
    [[languages.zh.menu.main]]
        name = "v0.19"
        url  = "http://v0-19.choerodon.io/zh/"
        weight = 26
        parent = "zh-version"
    [[languages.zh.menu.main]]
        name = "v0.20"
        url  = "http://v0-20.choerodon.io/zh/"
        weight = 27
        parent = "zh-version"
    [[languages.zh.menu.main]]
        name = "v0.21"
        url  = "http://v0-21.choerodon.io/zh/"
        weight = 28
        parent = "zh-version"
    [[languages.zh.menu.main]]
        name = "v0.22"
        url  = "http://v0-22.choerodon.io/zh/"
        weight = 29
        parent = "zh-version"

[params]
    viewMorePostLink = "/blog/"
    author = "Choerodon"
    tryhref = "https://choerodon.com.cn/#/iam/register-organization"
    signinhref = "https://choerodon.com.cn"
    ajaxhref = "https://share.choerodon.com.cn/topic/apply"
    praisenumber ="https://share.choerodon.com.cn/video/query"
    defaultKeywords = ["devops"]
    defaultDescription = ""
    # Format dates with Go's time formatting
    date_format = "2006-01-02"
